name: Build Paige

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        pyinstaller --noconfirm --onefile --windowed --name "Paige" --icon="assets/icon.ico" --add-data "assets;assets" main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Paige-Windows
        path: dist/Paige.exe

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/Paige.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

